import { apricot,geega,hajime,haruka,henya,ironmouse,kson,kuro,matara,melody,mochi,zentreya } from "../assets/img/Talents"

export const talents = [
    {
        name: "Apricot",
        twitterUrl: "https://twitter.com/LichVtuber",
        twitchUrl: "https://twitch.tv/apricot",
        youtubeUrl: "https://youtube.com/channel/UCtNeQ8cUwvAAhBbVbwfGWpg",
        backgroundColor: "#95F262",
        backgroundImage: apricot,
        quote: "You again?",
    },
    {
        name: "GEEGA",
        twitterUrl: "https://twitter.com/GeneralGEEGA",
        twitchUrl: "https://twitch.tv/GEEGA",
        youtubeUrl: "https://youtube.com/channel/UCUERxnZSjCq-G7OfYL7Nukg",
        backgroundColor: "#521830",
        backgroundImage: geega,
        quote: "It's not enough that I should win. Others should lose.",
    },
    {
        name: "Hime Hajime",
        twitterUrl: "https://twitter.com/HimeHajime_VSJ",
        twitchUrl: "https://twitch.tv/hajime",
        youtubeUrl: "https://youtube.com/channel/UCRfz2yOn8C7Jg5zq4Xi67-Q",
        backgroundColor: "#FDEDE0",
        backgroundImage: hajime,
        quote: "Ara ara",
    },
    {
        name: "Haruka",
        twitterUrl: "https://twitter.com/haruka_karibu",
        twitchUrl: "https://twitch.tv/harukakaribu",
        youtubeUrl: "https://youtube.com/channel/UCsk_mKQyv_xdhahUBqoVhcg",
        backgroundColor: "#A2DCA9",
        backgroundImage: haruka,
        quote: "HUEAGH!",
    },
    {
        name: "Henya the genius",
        twitterUrl: "https://twitter.com/HenyaTheGenius",
        twitchUrl: "https://twitch.tv/HenyaTheGenius",
        youtubeUrl: "https://youtube.com/channel/UCVhRMzNWYcg8XDTgB9NFRTw",
        backgroundColor: "#BEAEDB",
        backgroundImage: henya,
        quote: "IQ999",
    },
    {
        name: "Ironmouse",
        twitterUrl: "https://twitter.com/IronMouse",
        twitchUrl: "https://twitch.tv/ironmouse",
        youtubeUrl: "https://youtube.com/channel/UChgPVLjqugDQpRLWvC7zzig",
        backgroundColor: "#FF6799",
        backgroundImage: ironmouse,
        quote: "Hola hola holi, it is I... Sayton",
    },
    {
        name: "Kson",
        twitterUrl: "https://twitter.com/ksononair",
        twitchUrl: "https://twitch.tv/ksonsouchou",
        youtubeUrl: "https://youtube.com/channel/UC9ruVYPv7yJmV0Rh0NKA-Lw",
        backgroundColor: "#E55198",
        backgroundImage: kson,
        quote: "Always stay positive! And if people are negative, beat the shit out of them!",
    },
    {
        name: "Kuro Kurenai",
        twitterUrl: "https://twitter.com/K9_KURO",
        twitchUrl: "https://twitch.tv/k9kuro",
        youtubeUrl: "https://youtube.com/channel/UCN5J_HKNGFCPtqAnSjBekcA",
        backgroundColor: "#3A383B",
        backgroundImage: kuro,
        quote: "The darkness doesn't scare me. My only fear is losing who I am.",
    },
    {
        name: "Matara Kan",
        twitterUrl: "https://twitter.com/MataraKan",
        twitchUrl: "https://twitch.tv/MataraKan",
        youtubeUrl: "https://youtube.com/channel/UCxx2uRmAwkhb3QJMfLssgsw",
        backgroundColor: "#ba5da4",
        backgroundImage: matara,
        quote: "Bug me anytime you like, honey",
    },
    {
        name: "Projekt Melody",
        twitterUrl: "https://twitter.com/projektmelody",
        twitchUrl: "https://twitch.tv/projektmelody",
        youtubeUrl: "https://youtube.com/channel/UC1yoRdFoFJaCY-AGfD9W0wQ",
        backgroundColor: "#4EE0FA",
        backgroundImage: melody,
        quote: "what the FRICK?",
    },
    {
        name: "Michi Mochievee",
        twitterUrl: "https://twitter.com/MichiMochievee",
        twitchUrl: "https://twitch.tv/MichiMochievee",
        youtubeUrl: "https://youtube.com/channel/UCnS5IYNyGKOti9cFlK5SefQ",
        backgroundColor: "#B941FF",
        backgroundImage: mochi,
        quote: "*steals ur ****skin* teehee oops! well you probably didn't need it anyways! ✨ :3",
    },
    {
        name: "Zentreya",
        twitterUrl: "https://twitter.com/zentreya",
        twitchUrl: "https://twitch.tv/zentreya",
        youtubeUrl: "https://youtube.com/channel/UCVLsPBwDtv7n7FZLiOsvhSQ",
        backgroundColor: "#DC5953",
        backgroundImage: zentreya,
        quote: "Nice to meet you. I just downloaded your internet history.",
    },
]