import { apricot3,geega3,hajime3,haruka3,henya3,ironmouse3,kson3,kuro3,matara3,melody3,mochi3,zentreya3 } from "../assets/img/Talents"
import { apricot,geega,hajime,haruka,henya,ironmouse,kson,kuro,matara,melody,mochi,zentreya } from "../assets/img/Hero"
import { apricot2,geega2,hajime2,haruka2,henya2,ironmouse2,kson2,kuro2,matara2,melody2,mochi2,zentreya2 } from "../assets/img/Discover/index"
import { fullapricot,fullgeega,fullhajime,fullharuka,fullhenya,fullironmouse,fullkson,fullkuro,fullmatara,fullmelody,fullmochi,fullzentreya } from "../assets/img/Portfolio/index"


export const quotes = [
    "When having fun is the goal, there's room for everyone to succeed.",
    "Being you is the best avatar you could have.",
    "Filters help us take the mask off and show our true self."
];

export const talents = [
    {
        slug:"apricot",
        name: "Apricot",
        twitterUrl: "https://twitter.com/LichVtuber",
        twitchUrl: "https://twitch.tv/apricot",
        youtubeUrl: "https://youtube.com/channel/UCtNeQ8cUwvAAhBbVbwfGWpg",
        backgroundColor: "#95F262",
        heroColor: "#C4ECAE",
        backgroundTalent: apricot3,
        backgroundHero: apricot ,
        backgroundDiscover: apricot2,
        backgroundPortfolio: fullapricot,
        quote: "You again?",
        portfolio:"A bittersweet Lich who spends her days in her underworld castle drawing art. She took a turn to streaming once she realised she could harvest human souls by disguising them as Twitch Subscriptions. She is a hopeless necromantic and hopes to one day own her own Virtual Fashion brand.",
    },
    {
        slug:"geega",
        name: "GEEGA",
        twitterUrl: "https://twitter.com/GeneralGEEGA",
        twitchUrl: "https://twitch.tv/GEEGA",
        youtubeUrl: "https://youtube.com/channel/UCUERxnZSjCq-G7OfYL7Nukg",
        backgroundColor: "#521830",
        heroColor: "#EEE3D1",
        backgroundTalent: geega3,
        backgroundHero: geega,
        backgroundDiscover: geega2,
        backgroundPortfolio: fullgeega,
        quote: "It's not enough that I should win. Others should lose.",
        portfolio:"An optional MidBoss from a game called █████ looking for a side gig. She realized how easy it would be, as a 2-dimensional woman herself, to blend in with VTubers and create content from her home in the underworld and started up a channel or two. Her biggest loves are roguelikes, retro, and indie games.",
    },
    {
        slug:"hajime",
        name: "Hime Hajime",
        twitterUrl: "https://twitter.com/HimeHajime_VSJ",
        twitchUrl: "https://twitch.tv/hajime",
        youtubeUrl: "https://youtube.com/channel/UCRfz2yOn8C7Jg5zq4Xi67-Q",
        backgroundColor: "#FDEDE0",
        heroColor: "#FDDABE",
        backgroundTalent: hajime3,
        backgroundHero: hajime,
        backgroundDiscover: hajime2,
        backgroundPortfolio: fullhajime,
        quote: "Ara ara",
        portfolio: "A well-endowed Alien/Dragon/Robot hybrid from some far away planet. She decided to explore the universe but was drawn to Earth due to its variety of entertainment. Currently living in an old Japanese apartment but enjoys her time with videogames and alcohol. Often a bit crude but has a soft pleasant aura around her. Chose the name Hime Hajime from an 'eroge' as I think they call it on Earth?"
    },
    {
        slug:"haruka",
        name: "Haruka",
        twitterUrl: "https://twitter.com/haruka_karibu",
        twitchUrl: "https://twitch.tv/harukakaribu",
        youtubeUrl: "https://youtube.com/channel/UCsk_mKQyv_xdhahUBqoVhcg",
        backgroundColor: "#A2DCA9",
        heroColor: "#E1F4E3",
        backgroundTalent: haruka3,
        backgroundHero: haruka,
        backgroundDiscover: haruka2,
        backgroundPortfolio: fullharuka,
        quote: "HUEAGH!",
        portfolio:"A lonesome spirit that has lived through countless of lifetimes to learn to understand people. For Haruka, it is a never-ending journey, but with each connection she makes with someone, she takes that one step forward to becoming the person she wishes to be.",
    },
    {
        slug:"henya",
        name: "Henya the genius",
        twitterUrl: "https://twitter.com/HenyaTheGenius",
        twitchUrl: "https://twitch.tv/HenyaTheGenius",
        youtubeUrl: "https://youtube.com/channel/UCVhRMzNWYcg8XDTgB9NFRTw",
        backgroundColor: "#BEAEDB",
        heroColor: "#DACEEF",
        backgroundTalent: henya3,
        backgroundHero: henya,
        backgroundDiscover: henya2,
        backgroundPortfolio: fullhenya,
        quote: "IQ999",
        portfolio:`A genius with an IQ of 999. She has escaped from a research facility that gathers children with special abilities and has retreated into a hyperdimensional space to hide from her pursuers. The cube hanging from her neck occasionally glows blue-white and emits energy, charging all her electrical appliances so she doesn't have to charge her phone. She likes cats, games, and sweets, and her name Henya comes from the Spanish word Genia (genius), but even with an IQ of 999, she can't remember how to spell it, so she tells everyone "Henya" as she hears it.`,
    },
    {
        slug:"ironmouse",
        name: "Ironmouse",
        twitterUrl: "https://twitter.com/IronMouse",
        twitchUrl: "https://twitch.tv/ironmouse",
        youtubeUrl: "https://youtube.com/channel/UChgPVLjqugDQpRLWvC7zzig",
        backgroundColor: "#FF6799",
        heroColor: "#F7A4BF",
        backgroundTalent: ironmouse3,
        backgroundHero: ironmouse,
        backgroundDiscover: ironmouse2,
        backgroundPortfolio: fullironmouse,
        quote: "Hola hola holi, it is I... Sayton",
        portfolio:"A demon queen who goes by several names... but has also been rumored to be Satan herself. She is a friendly, fun loving demon who ran from her duties and escaped the confines of Hell/the underworld in order to make new friends, learn new things and live life to the fullest. She has an obsession with the internet, music, nerdy and all things cute. She wears special magical bells on her body to contain and control her power in order to better blend into the human world. If her bells ever get removed only pure chaos will ensue. It has been said that once the bells are off her true demon queen form will be revealed. All she ever wants to do is have fun and see what the human world is all about and consume... make as many souls friends as she can.",
    },
    {
        slug:"kson",
        name: "Kson",
        twitterUrl: "https://twitter.com/ksononair",
        twitchUrl: "https://twitch.tv/ksonsouchou",
        youtubeUrl: "https://youtube.com/channel/UC9ruVYPv7yJmV0Rh0NKA-Lw",
        backgroundColor: "#E55198",
        heroColor: "#F2C4DC",
        backgroundTalent: kson3,
        backgroundHero: kson,
        backgroundDiscover: kson2,
        backgroundPortfolio: fullkson,
        quote: "Always stay positive! And if people are negative, beat the shit out of them!",
        portfolio:"The former leader of a Japanese gang. After saying goodbye to each of her comrades as they moved on with their life, she became a lone rider... until she met a strange girl without memories.",
    },
    {
        slug:"kuro",
        name: "Kuro Kurenai",
        twitterUrl: "https://twitter.com/K9_KURO",
        twitchUrl: "https://twitch.tv/k9kuro",
        youtubeUrl: "https://youtube.com/channel/UCN5J_HKNGFCPtqAnSjBekcA",
        backgroundColor: "#3A383B",
        heroColor: "#FF757E",
        backgroundTalent: kuro3,
        backgroundHero: kuro,
        backgroundDiscover: kuro2,
        backgroundPortfolio: fullkuro,
        quote: "The darkness doesn't scare me. My only fear is losing who I am.",
        portfolio:"Undead god regaining powers, searching for his other half.",
    },
    {
        slug:"matara",
        name: "Matara Kan",
        twitterUrl: "https://twitter.com/MataraKan",
        twitchUrl: "https://twitch.tv/MataraKan",
        youtubeUrl: "https://youtube.com/channel/UCxx2uRmAwkhb3QJMfLssgsw",
        backgroundColor: "#ba5da4",
        heroColor: "#fae9f1",
        backgroundTalent: matara3,
        backgroundHero: matara,
        backgroundDiscover: matara2,
        backgroundPortfolio: fullmatara,
        quote: "Bug me anytime you like, honey",
        portfolio:"Bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug. Bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug. Bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug. Bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug bug.",
    },
    {
        slug:"melody",
        name: "Projekt Melody",
        twitterUrl: "https://twitter.com/projektmelody",
        twitchUrl: "https://twitch.tv/projektmelody",
        youtubeUrl: "https://youtube.com/channel/UC1yoRdFoFJaCY-AGfD9W0wQ",
        backgroundColor: "#4EE0FA",
        heroColor: "#B1E0E9",
        backgroundTalent: melody3,
        backgroundHero: melody,
        backgroundDiscover: melody2,
        backgroundPortfolio: fullmelody,
        quote: "what the FRICK?",
        portfolio:"Melody is a smol degenerate and adorable binary expression. She spends her time making unique content, and streaming from multiple platforms (some more cultured than others). Melody is a glitchy artificial intelligence, self-described as altruistic and moderately insane, as she's sometimes replaced by alter identities; the villainess Melware, and her gremlin side-kick Malady. She asks that her viewers prepare for a lot of swearing, sexual humor, and aggravating dad jokes.",
    },
    {
        slug:"mochi",
        name: "Michi Mochievee",
        twitterUrl: "https://twitter.com/MichiMochievee",
        twitchUrl: "https://twitch.tv/MichiMochievee",
        youtubeUrl: "https://youtube.com/channel/UCnS5IYNyGKOti9cFlK5SefQ",
        backgroundColor: "#B941FF",
        heroColor: "#D8A1EB",
        backgroundTalent: mochi3,
        backgroundHero: mochi,
        backgroundDiscover: mochi2,
        backgroundPortfolio: fullmochi,
        quote: "*steals ur ****skin* teehee oops! well you probably didn't need it anyways! ✨ :3",
        portfolio:"I'M MICHI MOCHIEVEE I STREAM AND HAVE BANGER MERCH. IT'S SUPER COOL, BOTH ARE SUPER COOL. I WON'T REMEMBER WRITING THIS AT ALL BUT TRUST ME IT'S SO COOL!!! BUY MY MERCH NOW & SUBSCRIBE TO MY CHANNELS CAUSE I'M SO COOLLLLL!!!",
    },
    {
        slug:"zentreya",
        name: "Zentreya",
        twitterUrl: "https://twitter.com/zentreya",
        twitchUrl: "https://twitch.tv/zentreya",
        youtubeUrl: "https://youtube.com/channel/UCVLsPBwDtv7n7FZLiOsvhSQ",
        backgroundColor: "#DC5953",
        heroColor: "#F3B9B7",
        backgroundTalent: zentreya3,
        backgroundHero: zentreya,
        backgroundDiscover: zentreya2,
        backgroundPortfolio: fullzentreya,
        quote: "Nice to meet you. I just downloaded your internet history.",
        portfolio:"A cyborg from a post-apocalyptic future, sent back in time to prevent the apocalypse. She's very headstrong and tends to yell at everyone around her, but loves meeting new people! She's become accustomed to 21st century culture, and enjoys memes and pranks.",
    },
]